language: php

php:
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: hhvm

install: travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
